[package]
publish = false
name = "example-custom-ops"
version = "0.0.0"
edition = "2021"

[dependencies]
ort = { path = "../../" }

[features]
load-dynamic = [ "ort/load-dynamic" ]

[[example]]
name = "custom-ops"
path = "custom-ops.rs"
